use_modular_headers!

target 'JJSocketManager_Example' do
    pod 'JJSocketManager', :path => '../', :modular_headers => true

  target 'JJSocketManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
