use_frameworks!

target 'JJSocketManager_Example' do
  pod 'JJSocketManager', :path => '../'

  target 'JJSocketManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
